name: Update README with Contributors

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run contributors-readme-action
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          image_size: 100
          readme_path: README.md
          use_username: false
          columns_per_row: 6
          collaborators: direct
          commit_message: docs(contributor): contrib-readme-action has updated readme
          auto_detect_branch_protection: true
          pr_title_on_protected: docs(contributor): contributors readme action update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
